/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Content type of a clipboard item */
export const enum ClipboardContentType {
  Text = 'Text',
  RichText = 'RichText',
  Image = 'Image',
  File = 'File',
  Link = 'Link',
  Color = 'Color',
  Unknown = 'Unknown'
}
/** Information about the source application */
export interface SourceAppInfo {
  bundleId: string
  name: string
}
/** A clipboard item captured from the system */
export interface NativeClipboardItem {
  /** Unique identifier */
  id: string
  /** Type of content */
  contentType: string
  /** ISO 8601 timestamp */
  createdAt: string
  /** Source application bundle ID */
  sourceAppBundleId?: string
  /** Source application name */
  sourceAppName?: string
  plainText?: string
  rtfData?: string
  htmlData?: string
  imageData?: Array<number>
  imageWidth?: number
  imageHeight?: number
  imageFormat?: string
  filePaths?: Array<string>
  detectedUrls?: Array<string>
}
/** Configuration for the clipboard monitor */
export interface ClipboardMonitorConfig {
  /** Polling interval in milliseconds (default: 500) */
  pollIntervalMs?: number
  /** Bundle IDs to exclude from monitoring */
  excludedBundleIds?: Array<string>
}
/** Read the current clipboard and return as a native item */
export declare function clipboardRead(): NativeClipboardItem | null
/** Get the current clipboard change count (for polling) */
export declare function clipboardChangeCount(): number
/** Example native function - returns a greeting */
export declare function greet(name: string): string
/** Example: Get system info (can be extended for macOS-specific features) */
export declare function getPlatformInfo(): string
